### ISSUE TITLE
Allow changing of clock time without triggering timeouts

### ISSUE THREAD

**Issue by johtso** [cjohansen/Sinon.JS#215]
I'm currently testing some code that reacts to javascript execution being paused for a period of time (for example a phone sleeping), and I wanted to simulate a pause in the javascript execution in my tests.

Currently `sinon.clock` will not run missed callbacks if you modify `clock.now` due to this check:
https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_timers.js#L167

```javascript
if (this.timeouts[id].callAt < from || this.timeouts[id].callAt > to) {
    continue;
}
```

Would be great if you could "warp" the clock without triggering timeouts, but still have the timeouts triggered the next time you tick.

**Comment by mroderick** [comment]
It's been a few years, I am closing this
