### ISSUE TITLE
Can't access to xhr in the function

### ISSUE THREAD

**Issue by ghost** [cjohansen/Sinon.JS#220]
I am trying to access to the xhr argument in a server function, but that is returning me "TypeError: Cannot call method 'respond' of undefined"

        var server = null, view = null;
          server = sinon.fakeServer.create();
          server.autoRespond = true;    

          server.respondWith(
            function (xhr) {
              console.log(xhr);
              xhr.respond(200, { "Content-Type": "application/json" }, dataFile);
            }

**Comment by mroderick** [comment]
Is this ticket still relevant?
