### ISSUE TITLE
XHR does not manage Blobs

### ISSUE THREAD

**Issue by TristanCavelier** [cjohansen/Sinon.JS#325]
I'm using Sinon.js 1.7.3 with Qunit on Firefox 23.0.1. I noticed that the fakeServer is not able to serve Blobs. When I create a GET XHR on a real server, I get this object:

    load event
    +-- target
        +-- response     Blob { size=3, .... }
        +-- responseText undefined
        +-- responseType "blob"

And when I create a GET XHR on a fake server, I get this object:

    Object
    +-- target
        +-- responseText "abc"
        +-- responseType "blob"

And `e.target.response` is missing!

**Comment by mroderick** [comment]
This ticket seems to be dead, I am closing it. If work will resume on it, please create new tickets.
