### ISSUE TITLE
fake POST request can have either data or success callback, but not both

### ISSUE THREAD

**Issue by mlibby** [cjohansen/Sinon.JS#340]
If time allows I will try to isolate a test case, but in my own tests I had a conflict between two tests that were using fake POSTs. One test was checking to make sure that the POST data was correct, the other test was checking that the success callback was triggering a behavior.

What I found is that it looks like a POST with data will clobber any success callback that is set. When I have POST data, the data test passed, but the callback test failed. If I removed the POST data, the data test failed (obviously) but the callback test passed.

What I noticed that was the expectation in the failing data test showed that the POST request body contained `success={Object object}`.

**Comment by mroderick** [comment]
If you find time, please re-open this issue, or create a new one.
