### ISSUE TITLE
sandbox.useFakeXMLHttpRequest is server instead of xhr

### ISSUE THREAD

**Issue by Krinkle** [cjohansen/Sinon.JS#393]
This seems rather confusing, was this on purpose or is this a bug?

[lib/sinon/sandbox.js#L120](https://github.com/cjohansen/Sinon.JS/blob/v1.8.1/lib/sinon/sandbox.js#L120):
```js
    sinon.sandbox.useFakeXMLHttpRequest = sinon.sandbox.useFakeServer;
```

As a result, code like the following (based on sinon-qunit documentation) doesn't actually work:
```js
QUnit.test('example', function (assert) {
    var xhr = this.sandbox.useFakeXMLHttpRequest(),
        requests = [];

    xhr.onCreate = function (request) {
        requests.push(request);
    };

    $.getJSON('/test');
    assert.equal(this.requests.length, 1);

    requests[0].respond(200, { 'Content-Type': 'application/json' }, '{}');
});
```

.. because that attaches a spurious `onCreate` method to the server object. The fake xhr manager is actually in `xhr.xhr` and the code is fixed when changed to `xhr.xhr.onCreate = function () { .. }`.

**Comment by gabrieledarrigo** [comment]
Hi,
even the new version use this:

```
sinon.sandbox.useFakeXMLHttpRequest = sinon.sandbox.useFakeServer;
````
?
