### ISSUE TITLE
sinon.stub().onCall(n) doesn't return a callback proxy

### ISSUE THREAD

**Issue by tinganho** [cjohansen/Sinon.JS#412]
If I just call `sinon.stub()` I get a function proxy:
![screen shot 2014-02-21 at 8 34 06 pm](https://f.cloud.github.com/assets/1324476/2229746/8d7bc062-9af4-11e3-9ca7-60c766fcf30f.png)
But if I call `sinon.stub().onCall(0).returns(false)` I got no function proxy:
![screen shot 2014-02-21 at 8 35 57 pm](https://f.cloud.github.com/assets/1324476/2229756/bcc8e598-9af4-11e3-8498-910804cb2f7d.png)

**Comment by mantoni** [comment]
This is correct. `sinon.stub()` returns a stub instance. `onCall(n)` returns a call object and `returns(false)` returns what is internally called a behavior.

If you have any question on how to use which, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.
