### ISSUE TITLE
Using sinon.assert with spyCall

### ISSUE THREAD

**Issue by vitalets** [cjohansen/Sinon.JS#580]
Hi, it seems using `sinon.assert` methods with [spyCall](http://sinonjs.org/docs/#spycall) not possible now. 
when trying:
````js
sinon.assert.calledWithMatch(mystub.firstCall, 83, {asd: 1});
````
I'm getting err like this:
````
AssertError: update(83, [object Object]) is not a function
````
Is it correct behavior? 
and if so, any plans to implement spyCalls like spies for assertion?
thanks!

**Comment by Asgaroth** [comment]
I am having the same issue, Ill try to send a PR this weekend.
