### ISSUE TITLE
Connection refused when using fake server

### ISSUE THREAD

**Issue by jesus-crysist** [cjohansen/Sinon.JS#582]
Hi,

I'm testing my Backbone model which uses remote server (different domain) to update it's state. For testing purposes I use chai and mocha-phantomjs plugins for grunt, which is used on our CI for running tests and build process.

Here is simplified code I used:
``` javascript
describe(function () {

var model = new MyModel();

// Sinon setup
beforeEach(function () {
    this.ajaxSpy = spy($, 'ajax');
    this.server = sinon.fakeServer.create();
});

afterEach(function () {
    $.ajax.restore();
    this.server.restore();
});

it('should connect to server', function () {

this.server.respondWith("POST", "https://remote.url.com/some/path?sid=SOMESID",
    [ 200, {'Content-Type': 'application/json' }, JSON.stringify(responseMock) ] );

myModel.initConnection(); // this is where I initiate connection to the server

this.server.respond();

myModel.syncSpy.calledOnce.should.be.true; // this passes when I don't make the connection
myModel.should.contain.keys('someDataFromServer');
```

As a result in the browser console I get:
```
OPTIONS https://remote.url.com/some/path?sid=SOMESID net::ERR_CONNECTION_REFUSED fake_xml_http_request.js?bust=1413984248420:155
```

There I figured out that I can't "send" data to the fake server has other origin and tried to create OPTIONS response. Instead of returning "Allow-Origin" and other CORS headers, I saw in my Chrome's Web inspector that all those CORS headers exist in request instead in response.

My question here is do you support cross-origin with fakeServer? And if you don't will you do it in the future?

Cheers,
Jovica

P.S. For now, in my tests I'll just use fake URL that belongs to the same origin.

**Comment by mroderick** [comment]
Is this issue still relevant?

**Comment by Dakuan** [comment]
I'm running into something similar when using relative urls

this gets captured by sinon:
``` javascript
request.del('http://thing.com/api/items/' + id) // returns whatever is configured in sinon
```

this does not:
``` javascript
request.del('/api/items/' + id) // dreaded ECONNREFUSED error
```

**Comment by mroderick** [comment]
@Dakuan if you feel you have run into a defect with Sinon, please open a separate ticket with precise instructions on how to reproduce the issue. We have [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue)

If you think that your issue is more of a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs)

**Comment by bryancallahan** [comment]
@Dakuan did you ever open a ticket for this issue?
