### ISSUE TITLE
fakeServer not Working in IE9

### ISSUE THREAD

**Issue by josiahsprague** [cjohansen/Sinon.JS#584]
I've got `fakeServer` working in all browsers except IE9. I'm not seeing any errors in IE9, I just get a response from the real server instead of `fakeServer`. It looks like [`XDomainRequest` support was added in May](https://github.com/cjohansen/Sinon.JS/blob/master/Changelog.txt#L18), so I'm not sure what is going wrong.

This is basically how I'm setting up the `fakeServer`. My app takes care of defining `url` and `response`;

```
server = sinon.fakeServer.create();
server.autoRespond = true;

server.respondWith(url, function(r){
  r.respond(
    200,
    {"Content-Type":"application/json"},
    response
  );
});
```

And here's my function that creates the CORS request;
```
function _createCorsRequest(method, url, data) {

    var xhr;
    if ('withCredentials' in new XMLHttpRequest()) {
      xhr = new XMLHttpRequest();
      xhr.open(method, url, true);
    } else if (typeof XDomainRequest != 'undefined') {
      xhr = new XDomainRequest();
      //The next 6 lines must be defined here or IE9 will abort the request
      xhr.timeout = 3000;
      xhr.onload = function(){};
      xhr.onerror = function (){};
      xhr.ontimeout = function(){};
      xhr.onprogress = function(){};
      xhr.open('POST', url + '?' + data);
    } else {
      xhr = null;
    }
    return xhr;
}
```

Do I need to configure something differently in order for `fakeServer` to respond to an `XDomainRequest`?

**Comment by matz3** [comment]
This change now breaks the fakeServer to respond to an XMLHttpRequest in IE9 which is a valid use case in my opinion. I am not using XDomainRequest as my scenario doesn't require it.

Is there any other solution than setting `sinon.xhr.supportsCORS = true;` in case of IE9 ?

**Comment by mroderick** [comment]
> This change now breaks the fakeServer to respond to an XMLHttpRequest in IE9 which is a valid use case in my opinion. I am not using XDomainRequest as my scenario doesn't require it.
>
> Is there any other solution than setting sinon.xhr.supportsCORS = true; in case of IE9 ?

Thank you for your feedback :ice_cream: 

Could you describe the error in a new ticket with instructions on how to reproduce it? We have a [little guide to effectively reporting issues](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue) in CONTRIBUTING.md

**Comment by moll** [comment]
This change also seems to interfere with using Sinon on Node.js, where the fake server now tries to use XDomainRequest because `global.XMLHttpRequest` does not exist. Of course it doesn't, that's why we use Sinon to fake it. ^_^
