### ISSUE TITLE
stubs do not have the same arity as the functions they replace

### ISSUE THREAD

**Issue by tmfset** [cjohansen/Sinon.JS#598]
Node v0.10.26
Sinon v1.11.1

Normally this wouldn't be a problem. The reason I noticed this is because I want to stub a function that I will later curry. Without the correct arity, the curry function cannot work as is should.

Here is a minimal example:

```javascript
var sinon = require('sinon');

var obj = { fn: function (a,b) { } }

console.log(obj.fn.length);
sinon.stub(obj, "fn");
console.log(obj.fn.length);

```

Expected output:
```
2
2
```

Actual output:
```
2
0
```

**Comment by mroderick** [comment]
@tmfset Thank you for reporting this, it looks like an interesting one to solve :+1: 

Have you managed to fix this yourself, or come up with a workaround in the meantime?

**Comment by tmfset** [comment]
Yes there is a workaround for this, I suppose I should have posted it :)

Taking my example above, instead of stubbing like this:

    sinon.stub(obj, "fn");

one can fill in a small stub function of their own with the correct arity:

    sinon.stub(obj, "fn", function (a,b) { })

This can be enough for simple cases, but it has some problems. For one, if the arity of the function ever changes, you will have to correct any tests that stub it.

**Comment by mantoni** [comment]
I remember fixing this for spies here: https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/spy.js#L65
We should do something the like for stubs as well.

**Comment by BigstickCarpet** [comment]
:+1:   
This is the only reason I can't use Sinon stubs when testing [Express.js](http://expressjs.com/) apps.  Express determines the middleware type by its arity.
