### ISSUE TITLE
Provide access to real XMLHttpRequest object

### ISSUE THREAD

**Issue by raffomania** [cjohansen/Sinon.JS#616]
I'd like to implement a proxy in sinon. I tried restoring, sending the request to the real server and then creating the fake server again, which doesn't work because sinon invalidates requests upon restoring. It would be really nice to be able to access the real XMLHttpRequest to send actual, working AJAX requests.

**Comment by mroderick** [comment]
> Based on the code, it looks like there's a copy of the original XHR stored at sinon.xhr.XMLHttpRequest. Is this not the case?

I wouldn't bet on that being available in `2.0`. We're hoping to tidy up the API considerably.

**Comment by mroderick** [comment]
This has been resolved with https://github.com/sinonjs/sinon-docs/pull/7
