### ISSUE TITLE
The sinon.useFakeTimers() method without passing arguments works unexpectedly

### ISSUE THREAD

**Issue by San4es** [cjohansen/Sinon.JS#636]
I believe that the method useFakeTimers without timestamp passing should use Date.now as it, but not 0:

     sinon.useFakeTimers = function () {
            var now, methods = Array.prototype.slice.call(arguments);

            if (typeof methods[0] === "string") {
                now = 0; // Why not use Date.now here?
             ...

See demo: http://jsfiddle.net/h5znwaqc/
Compare results with: http://jsfiddle.net/91Lo98c8/

**Comment by duncanbeevers** [comment]
Using a consistent epoch keeps tests reproducible. If the spec you're running depends on time being seeded to a certain value, that avenue is available, but as a rule, test inputs should remain stable from run to run.

**Comment by cjohansen** [comment]
Pretty much
