### ISSUE TITLE
Redefine stub behavior

### ISSUE THREAD

**Issue by hurrymaplelad** [cjohansen/Sinon.JS#643]
I sometimes like to enforce that at the suite level that included test must stub a behavior, like `$.ajax`.  With jasmine, I can 

    spyOn($, 'ajax').andCallFake(function() {throw new Error('...')})

then per spec

    $.ajax.andReturn($.Deferred(...))

I'd like to do the same with sinon:

    before(function() {
        sinon.stub($, 'ajax').throws(new Error('...'))
    });

    beforeEach(function() {
        $.ajax.returns($.Deferred(...))
    })

But the `returns` can't clobber the original `throws`.  Would you take a pull request to make this work?
    });

**Comment by cjohansen** [comment]
I'm skeptical of this approach, as I've seen it create illegible and unstable tests too many times, but I'm a little torn on adding this feature. I'm leaning towards "nah", but maybe @mantoni or @mroderick want to have an opinion as well?

**Comment by mantoni** [comment]
Hm. There is `resetBehavior()`, a hidden "feature" of sorts. Would it make sense to use it in this case?

**Comment by hurrymaplelad** [comment]
It's strange to me that I can redefine what a spy returns, but I can't switch from throwing to returning. For example:

```js
before(function() {
    sinon.stub($, 'ajax').returns(new Error('...'))
});

beforeEach(function() {
    $.ajax.returns($.Deferred(...))
})
```
works today.  If instead we want to discourage this approach, should we prevent redefining returns too?

**Comment by cjohansen** [comment]
You're right. I'll take a pull request for your original suggestion ;)

**Comment by hurrymaplelad** [comment]
Hrm, @cjohansen looks like this was reverted in https://github.com/cjohansen/Sinon.JS/commit/378eea5dcfff9d8ff27ef92af9e11f0252564733 along with the intended #653.  Intentional?  Was hoping to use this feature...

**Comment by hurrymaplelad** [comment]
Also, if you have an example of an illegible or unstable mess this approach leads to, I'd love to learn from it before I get there myself.  So far, only joy when I've used it :)
