### ISSUE TITLE
createServer not working with jQuery-1.11.2 embedded in a local file

### ISSUE THREAD

**Issue by WaffleSouffle** [cjohansen/Sinon.JS#645]
jQuery-1.11.2 chooses whether to use `createStandardXHR()` (returning an `XMLHttpRequest`) or `createActiveXHR()` (returning an `ActiveXObject`) depending on whether the url is "local", based on a regular expression including testing for the the string prefix "file".

Running tests from Visual Studio 2013 launches a local html file. This is treated as local, so a `window.ActiveXObject("Microsoft.XMLHTTP")` is used. Note that the test for the existence of `window.ActiveXObject` is made using `window.ActiveXObject !== undefined`.

sinon-1.12.2 line 4031 setup uses `global.ActiveXObject` detection to establish whether it should support ActiveX.

Seeing a reproducible issue in IE11 running as Edge where evaluating `typeof global.ActiveXObject` returns `"undefined"`. There is a lot of inconsistent behaviour based around this property in IE11.

The watches shows that `window` has no `ActiveXObject` property. However, hovering over `window.ActiveXObject` shows a function.
Calling `window.ActiveXObject('Microsoft.XMLHTTP')` at this point in the console returns "Object doesn't support this action", rather than "Object doesn't support property or method 'ActiveXObject'".

`typeof window.ActiveXObject` returns `"undefined"`.
`window.ActiveXObject !== undefined` returns `true`.
`console.log(window.ActiveXObject)` shows 
`function ActiveXObject() {
    [native code]
}`

Fix is to include a test for undefined. Pull request is pending.

**Comment by cjohansen** [comment]
Thanks, fixed here: https://github.com/cjohansen/Sinon.JS/commit/951a4dabd77a67019c5021c2927f26b821c19e89
