### ISSUE TITLE
async jQuery callback support with sinon.server.autoRespond

### ISSUE THREAD

**Issue by gregor-w** [cjohansen/Sinon.JS#649]
For now it seems autoRespond will not work if you use async jQuery calls. Callback.called is never true. Please enable this scenario so that I do not have to manually call server.respond()

**Comment by GCheung55** [comment]
Do you have an example to reproduce the issue?

**Comment by gregor-w** [comment]
````coffeescript
describe 'Service', ->
  server = null
  urls =
    rest_url: 'http://localhost'
    websocket_url: 'wss://localhost'

  service = null

  beforeEach ->
    server = sinon.fakeServer.create()
    server.autoRespond = true
    server.autoRespondAfter = 0

    service = new service_xyz

  afterEach ->
    server.restore()

  it 'can get an async server response', ->
    request_url = "#{urls.rest_url}/service_endpoint"
    server.respondWith 'GET', request_url, [
      200
      {'Content-Type': 'application/json'}
      {'answer':'Interesting JSON stuff'}
    ]
    callback = sinon.spy()

    service.get_answer callback

    expect(callback.called).toBeTruthy()
````

And `service_xyz.get_answer` does something like this:

````coffeescript
    $.ajax
      crossDomain: true
      contentType: 'application/json; charset=utf-8'
      type: 'POST'
      url: "#{urls.rest_url}/service_endpoint"
    .done (data, textStatus, jqXHR) =>
      callback? data
    .fail (jqXHR, textStatus, errorThrown) =>
      callback? null, jqXHR.responseJSON or errorThrown
````

`callback.called` will always be false. I have to add a  `server.respond()` after the making the service call for it to be true.

**Comment by GCheung55** [comment]
Your test looks to be synchronous. `service.get_answer` is executed and immediately the `expect` is executed without waiting for the `callback` to complete.

Perhaps you could change that test to wait for the callback to be executed before continuing?

Excuse the JS, I'm not familiar with coffee.

```javascript
// I don't know if the test runner you are using passes in a "done" callback,
// but it would be used for async tests to notify the test runner that the test is complete.
// Check with your test framework to see how async tests are handled.

it('can get an async server response', function(done){
    /* your other code */
    var callback = sinon.spy(function(){
        expect(callback.called).toBeTruth()
        done()
    })

    service.get_answer(callback)
})
```

**Comment by gregor-w** [comment]
@GCheung55 Thanks for helping me out with this issue. I am using Jasmine as the test runner. They used to have a run/waitsFor for async stuff but that has be deprecated in favor of the beforeEach. They do not have a done on the it block but on the before each.

I have modified my code to this with no avail:

````coffeescript
describe 'Service', ->
  callback = null
  server = null
  urls =
    rest_url: 'http://localhost'
    websocket_url: 'wss://localhost'

  service = null

  beforeEach (done) ->
    server = sinon.fakeServer.create()
    server.autoRespond = true
    server.autoRespondAfter = 0

    service = new service_xyz
    request_url = "#{urls.rest_url}/conversations/last-events"
      server.respondWith 'GET', request_url, [
        200
        {'Content-Type': 'application/json'}
        JSON.stringify payload.conversations.last_events.get
      ]
      callback = sinon.spy(done) ->
        expect(called).toBeTruthy()
        done()

      conversation_service.get_last_events callback

  afterEach ->
    server.restore()

  it 'can get an async server response', ->
    expect(callback.called).toBeTruthy()
````

**Comment by mroderick** [comment]
@gregor-w this doesn't look like a Sinon.JS issue to me, more like a Jasmine issue. Have you found a resolution to it?

It seems that [async things are moving in Jasmine land](https://github.com/jasmine/jasmine/issues/749) these days.

**Comment by mroderick** [comment]
> Please enable this scenario so that I do not have to manually call server.respond()

Please see http://sinonjs.org/docs/#auto-respond, where it's clearly stated that 

> this feature is intended to help during mockup development, and is not suitable for use in tests

**Comment by gregor-w** [comment]
@mroderick Seems like you are right with the autoRespond. So I will stick with the server.respond() after each async call. I also run into this issue with CasperJS though. Tried to get the autoRespond working in Jasmine to see how to do in casper. Because in casper I do not have access to my server variable no matter what I do - even when I declare it on window.

````coffeescript
casper.on 'load.finished', (resource) ->
  @evaluate (() ->
    @urls =
      rest_url: 'http://localhost:8889'
      websocket_url: 'wss://localhost'

    window.server = sinon.fakeServer.create()

    request_url = "#{@urls.rest_url}/login"
    server.respondWith 'POST', request_url, [
      200
      {'Content-Type': 'application/json'}
      JSON.stringify payload.login.post
    ]
  )

casper.on 'remote.message', (message) ->
  @echo message if not (message.indexOf('Websocket') !=-1)

casper.test.begin 'Login tests', {
  setUp:  ->
    # Some unrelated stuff

  tearDown: ->
    # More unrelated stuff

  test: ->
    casper.start 'http://localhost:8888/login.html', ->
      @test.assertTitle 'Login'

    casper.then ->
      @test.assertExists 'form#login-form'
      @fillSelectors 'form#login-form',
        'email': 'xyz@abc.com'
        '#password': 'qwertzui'
      , true
      window.server.respond()

    casper.waitForUrl 'http://localhost:8888/index.html', ->
      @test.comment 'Login succeeded'
      @test.assertExists '#main'
````

It never finds server in this case and thus the async call is never answered.

**Comment by freethejazz** [comment]
@gregor-w See my [proposed enhancement](https://github.com/cjohansen/Sinon.JS/issues/285#issuecomment-77784452) addressing your initial request. Is that what you had in mind?
