### ISSUE TITLE
 Mocking a method's response using SinonJS

### ISSUE THREAD

**Issue by prachicsa** [cjohansen/Sinon.JS#654]
I am very new to testing world. I have a following function:

```
exports.get = function (para1) {
    var response = querySys(para1);
    response.in = 1;
    return response;
}
```

I want to mock the result of ```querySys``` method.

I want it to return ```{in: 0, out: 1}```.

So how do I do it with Sinon? Do I have to mock it or stub it?

**Comment by mroderick** [comment]
You would stub it

http://sinonjs.org/docs/#stubs
