### ISSUE TITLE
how to use fake server for image load?

### ISSUE THREAD

**Issue by vitalets** [cjohansen/Sinon.JS#656]
hi, 

I'm successfully use sinon fake server for mocking xhr requests.
But also I need to mock image load requests e.g. `image.src = 'http://example.com/img.jpg'`
Is it possible somehow?

**Comment by mantoni** [comment]
No, this is not possible. But why not fetch the image(s) from the DOM and assert the `src` property?

**Comment by vitalets** [comment]
hi @mantoni 

thanks for the reply!
Could you show example what do you mean under "But why not fetch the image(s) from the DOM and assert the src property" ?

**Comment by mroderick** [comment]
@vitalets do you need to verify that the image is requested on the network by the browser, or that it is correctly inserted into some html, like verifying template output?

If the latter is the case, you can use [data-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs) as the src attribute on the image, and detect the string in the HTML. I've done this in a few projects now, it's a technique that works well, and doesn't generate network requests.

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
