### ISSUE TITLE
stub a module which is a function?

### ISSUE THREAD

**Issue by kevinburke** [cjohansen/Sinon.JS#664]
say I have something like

##### hardwork.js

```javascript
module.exports = function(req, res, next) {
     // do some async-heavy work, then:
     next()
}
```

I want to stub this function directly. Something like

```javascript
hardwork = require('./hardwork');

sinon.spy(hardwork, function(req, res, next) { next() });
```

Is there a way to do this? I read through the documentation, but it seems way more geared to stubbing methods on objects. Unfortunately in this case it's not straightforward to make the function a method on an object.

**Comment by gyandeeps** [comment]
I had the same concern and later i had to change the code of the module a little bit so that I can stub it easily. 
So according to your case thats  what I did:

**hardwork.js**

```.js
function thisWay(req, res, next) {
     // do some async-heavy work, then:
     next()
}

module.exports.thisWay = thisWay;
```

This is how I used `stub` on it

```.js
var hardwork = require('./hardwork');

var stub = sinon.stub(hardwork, "thisWay");
```

**Comment by cjohansen** [comment]
Doing this is not technically possible without faking the entire module loading system.

**Comment by kevinburke** [comment]
hi christian! thanks for writing back, and thanks for your work on the
library.

Would you consider posting this information somewhere in the documentation?
I searched for a fair amount of time today for an answer to this question -
at least to me as a Node newbie, it seemed like there shouldn't be too much
difference between stubbing a function and stubbing a property of an
object, though clearly there is.


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by gyandeeps** [comment]
@kevinburke here is something you might want to look at:
https://github.com/thlorenz/proxyquire

**Comment by tomatau** [comment]
Hit the same problem today after fighting for several hours.. Can't stub vendor libraries that expose this kind of API.

Working with proxy/injecting module systems is not always possible with builds such as babeljs + webpack inside tests.

Would be great if this could be explored more - not sure why it wouldn't be possible to modify the function object reference:
```
// declare function foo
var foo = function (a) { alert(a); };

// modify function foo
// modify function foo
foo = new Function (
  "a",
  foo.toSource()
    .replace("alert(a)", "alert('function modified - ' + a)")
    .replace(/^function[^{]+{/i,"")  // remove everything up to and including the first curly bracket
    .replace(/}[^}]*$/i, "")  // remove last curly bracket and everything after<br>
);
```

**Comment by fabiosantoscode** [comment]
According to the node docs, `require` has a `cache` property which caches required modules. If you are the first to require the stubbed module, you can stub the function right in require.cache.

https://nodejs.org/api/globals.html#globals_require_cache

If you don't want to hack node's require system, you can put your function in a property in module.exports. Then assign module.exports to a function which calls module.exports.yourOriginalFunction with the provided arguments. Then you can stub your original function.

**Comment by tomatau** [comment]
functions don't keep their reference so stubbing it will change the ref and the original inclusion won't be updated. afaik. 

What I do here is wrap function's exposed by modules inside another module that wraps the said function in an object that can be stubbed easily.

**Comment by fabiosantoscode** [comment]
> functions don't keep their reference so stubbing it will change the ref and the original inclusion won't be updated. afaik.

Exactly, but that is not a problem if your wrapper calls module.exports.functionName instead of functionName.

Then if you stub module.exports's "functionName" the function will call the stub instead.

**Comment by tomatau** [comment]
I've been working in a webpack environment using `exports default` which doesn't have the same behaviour as module.exports.

**Comment by fabiosantoscode** [comment]
I see now, that makes sense

**Comment by vitalets** [comment]
Another options is https://www.npmjs.com/package/require-subvert but in our team we just decieed to export objects.
