### ISSUE TITLE
spy().reset() return this

### ISSUE THREAD

**Issue by shakiba** [cjohansen/Sinon.JS#675]
Is there any way to extend Sinon so that it returns same object after calling reset()? Or can I request to make this change to Sinon?

**Comment by mantoni** [comment]
You can also send a pull request with this feature ;-)

**Comment by shakiba** [comment]
Sure, but isn't there any reason that it has not been done yet?

**Comment by mantoni** [comment]
No. Me, for example, I only use reset in `afterEach`. I can't think of anything else that `reset()` should return, so `return this;` is fine.
