### ISSUE TITLE
How to get a release?

### ISSUE THREAD

**Issue by Asgaroth** [cjohansen/Sinon.JS#682]
How can we get/generate a release that contains the following commit? 

https://github.com/cjohansen/Sinon.JS/commit/79d3ee14aeb1fe07155c58f3469b31eff3950d23

couldn't find instructions and seems like the [sinon-web](https://github.com/cjohansen/sinon-web) repo is not what its beign used?

**Comment by mroderick** [comment]
@Asgaroth I've poked @cjohansen a couple of days ago about a new release, and about releasing more often. It shouldn't be long now :)

**Comment by Asgaroth** [comment]
Awesome :smiley:

**Comment by cjohansen** [comment]
Sorry, I've been traveling since the ping. I'll get something together shortly.

**Comment by freethejazz** [comment]
I believe this is done, can the issue be closed?

**Comment by Asgaroth** [comment]
Yes thanks!
