### ISSUE TITLE
How to spy nested function call

### ISSUE THREAD

**Issue by hellboy81** [cjohansen/Sinon.JS#688]
Assume `db` is `mongo` instance.

I can create spy `collection`call with

```js
var colSpy = sinon.spy(db, 'collection')
```

How can I create spy for this call?

```js
db.collection(myColName).update(..., ...)
```

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by hellboy81** [comment]
See discussion [How to spy nested function call](https://groups.google.com/forum/#!searchin/sinonjs/mongo$20sinon/sinonjs/W_CclBb7JU8)
