### ISSUE TITLE
Feature proposal: yieldsLast

### ISSUE THREAD

**Issue by lxanders** [cjohansen/Sinon.JS#689]
The current implementation of `yields` calls the first callback it identifies with the arguments specified. This is most of the time sufficient.

There are however situations where more than one function is passed into a function so yielding is limited here.

```js
// in any module
module.exports = {
    foo: function (anyFunction, anyData, callback) {
        var result = anyData;

        if (!result) {
            return callback(new Error('any error'));
        }

        return callback(null, result);
    }
};

// in the test
var sinon = require('sinon'),
    anyModule = require('./anyModule'),
    anyData = { any: 'data' },
    anyResult = { any: 'result' },
    anyFunction = function () {
        console.log('first function called:', arguments);
    }
    callback = function (error, result) {
        console.log('callback function called:', arguments);
    },
    foo;

foo = sinon.stub(anyModule, 'foo');
foo.yields(null, anyResult);

foo(anyFunction, anyData, callback);
```

As expected, the result is that `anyFunction` is called with the parameters specified in the `yields` statement. The callback function which is the last argument for `foo` is not called at all.

This could be solved by adding a `yieldsLast` feature that yields not for the first but for the last function argument found (`callback` in the example above). 

I'm aware of the `callsArg` function which can be used to call a callback function at a specified arguments index. For this to work you need to know the exact index of the callback which is not very convenient.

If there is interest in this feature I would look into it if I'm able to send a pull request for it.

**Comment by cjohansen** [comment]
Sounds good to me! Just a suggestion, but would "yieldsRight" work as a name? I'm not sure which one I prefer myself...

**Comment by lxanders** [comment]
Great that you like the idea! `yieldsRight` works even better for me than `yieldsLast`. I will work on a solution this week.
