### ISSUE TITLE
Feature proposal: allow user to set specific delay on callback execution

### ISSUE THREAD

**Issue by erikgui** [cjohansen/Sinon.JS#691]
I am trying to write some tests that needs callbacks to be called after a certain delay. Is it possible for `callsArgAsync` to take a parameter that specifics the exact delay time?

**Comment by mantoni** [comment]
How about just doing `setTimeout(function () { stub.yield(); }, myTimeout)`?

**Comment by erikgui** [comment]
I'm trying to do `sinon.stub(component, "request").callsArgWithAsync(callbackIndex, data)`. Following your example, I suppose this works:
```
sinon.stub(component, "request", function() {
        var callback = arguments[callbackIndex];
        setTimeout(function() {
          callback(data);
        }, myTimeout);
}
```
Is that the best way to do it?

**Comment by mantoni** [comment]
If you want to specify the behavior up front, then yes. You could alternatively write it like this:

```js
sinon.stub(component, "request");
// ...
setTimeout(function () {
  component.request.callArgWith(callbackIndex, data);
}, myTimeout);
```

I see now that it's a bit much to read / write, but it's a very special case and I don't think it's worth adding more API to Sinon. More thoughts @cjohansen @mroderick?

**Comment by cjohansen** [comment]
I don't really see the general use of a specific abstraction for this either.

**Comment by erikgui** [comment]
Hmm I see. Thanks for your help! @cjohansen @mantoni
