### ISSUE TITLE
Publish 1.13.0 to npm

### ISSUE THREAD

**Issue by joeybaker** [cjohansen/Sinon.JS#701]
Looks like an oversight?

**Comment by mroderick** [comment]
It hasn't been tagged either, so I guess Christian is just preparing everything.

**Comment by cjohansen** [comment]
I prepared the release last night, watched some TV and forgot to publish ;) It's out now

**Comment by mantoni** [comment]
:tv: :+1:

**Comment by joeybaker** [comment]
Thanks! 

FWIW, I'm not sure it's of interest, but I've got an NPM script that can automate a release for you: https://github.com/joeybaker/generator-iojs/blob/master/package.json#L20
