### ISSUE TITLE
sinon.test is broken

### ISSUE THREAD

**Issue by mohayonao** [cjohansen/Sinon.JS#702]
on v1.13.0

```js
describe("sinon.test", function() {
  it("works?", sinon.test(function(done) {
    done(); // undefined is not a function
  });
});
```

https://github.com/cjohansen/Sinon.JS/commit/5b47ab5b500de1fbeb229bc1bc93f4c272e46740#diff-9b1597fcd86fcb2f9919de55d87e6af5L68

I think the argument `callback` of `sinonAsyncSandboxedTest` is necessary for mocha async test.

**Comment by SamVerschueren** [comment]
Ran into this issue aswell today. Reverted back to v1.12.2 for now.
