### ISSUE TITLE
Request: support ArrowFunction in sinon.test

### ISSUE THREAD

**Issue by mohayonao** [cjohansen/Sinon.JS#704]
I want to use sinon with ES6(babel), but the below code doesn't work.
Because `sinon.test` binds a sandbox to `this`, but ArrowFunction doesn't accept it.

```js
describe("sinon.test", () => {
  it("works", sinon.test(() => {
    this.spy(); // TypeError: undefined is not a function
  });
});
```

Proposal
- Add new interface
- The new interface gives a sandbox object as the first argument to a callback of sinon.test.

```js
// should name more better
sinon.test2 = function(fn) {
  if (1 < fn.length) {
    return sinon.test(function(done) {
      var args = Array.prototype.slice.call(arguments, 1);
      return fn.apply(this, [ this, done ].concat(args));
    });
  } else {
    return sinon.test(function() {
      return fn.call(this, this);
    });
  }
};

describe("sinon.test", () => {
  it("works", sinon.test2((sandbox) => {
    sandbox.spy();
  });
});
```

**Comment by freethejazz** [comment]
Hey @mohayonao, you can still use sinon with ES6. In this case, you'll want to use the `function () {...}` which is still a part of the spec. The `=>` syntax is not simply syntactic sugar for `function () {...}`, it varies in several ways including the value of the `this` keyword. You'll likely run into problems using `=>` in other libraries as well if they expect to be able to use `call()` or `apply()`.

If you really really want to use `=>` with `sinon.test`, look at the `injectIntoThis` and `injectInto` properties of `sinon.config`. I haven't used this before, but I believe this is the gist of it:

```
describe("sinon.test", () => {
  var sandboxObject = {};
  sinon.config = {
    injectIntoThis: false,
    injectInto: sandboxObject
  };

  it("works", sinon.test(() => {
    sandboxObject.spy(); // Works as expected
  });
});
```

**Comment by mohayonao** [comment]
thanks @freethejazz

I understand the difference between Function and ArrowFunction.
I don't want to write those mixture, but this issue was self-centered request.

```js
describe("sinon.test", () => {
  it("works", sinon.test(function() { // not cool..
  });
});
```

**Comment by cjohansen** [comment]
The `sinon.config` stuff is really weird, and I want to change it for Sinon 2.0. Anyway, you can do this:

```js
sinon.config = { injectIntoThis: false };
sinon.test(function (spy, stub, mock) {
  spy(obj, "meth");
  // ...
});
````

Or this:

```js
sinon.config = { injectIntoThis: false, properties: ['sandbox'] };
sinon.test(function (sandbox) {
  sandbox.spy(...)
});
```

**Comment by mohayonao** [comment]
:+1:
