### ISSUE TITLE
How to deal with web sockets?

### ISSUE THREAD

**Issue by binarykitchen** [cjohansen/Sinon.JS#706]
We have built a small fake server based on sinon to simulate some app logic. But we want to pass through some requests to the server, for example Browser Sync's pollings for automatic browser refresh during development. But these perform a GET request and have a web socket mechanism. Somehow Sinon is blocking these.

Has anybody else dealt with this before?

If you could look at the code in https://github.com/BrowserSync/browser-sync/issues/504, that would be great. Not sure what the issue is here. Thanks for helping!

**Comment by gyandeeps** [comment]
Use `filters` to fake and defake certain request. That what I did.

```.js
var server = sinon.fakeServer.create();
server.xhr.useFilters = true;
server.autoRespond = true;

//Don't fake socket.io calls
server.xhr.addFilter(function(method, url, async, username, password){
    if((new RegExp("socket", "i")).test(url)){
        return true;
    }
});
```

**Comment by binarykitchen** [comment]
Thanks!
