### ISSUE TITLE
Linting is inconsistent

### ISSUE THREAD

**Issue by freethejazz** [cjohansen/Sinon.JS#707]
The docs state linting can be accomplished via either `npm run lint` or, if `jscs` is installed globally, `jscs .`.

On the current state of master, `npm run lint` returns no errors.
`jscs .` returns 135 errors.
`jscs **/*.js`, which is what the lint script in package.json is supposed to run, returns 10 errors.
`$(npm bin)/jscs .`, which is what travis runs, returns 0 errors.

Adding a single error, changing an `if (...)` to `if(...)` (removing the space), results in:

`npm run lint` -> no errors
`jscs .` -> 136 errors 
`jscs **/*.js` -> 10 errors
`$(npm bin)/jscs .` -> 1 error

I'd be happy to help with a PR on this one given some guidance on which linting approach is desired.

**Comment by cjohansen** [comment]
Huh. When `package.json` says to run `jscs **/*.js`, that actually means `$(npm bin)/jscs **/*.js` as the binary directory is added to the path before running the script.

I would think that the `package.json` version is the right one, but I'm going to defer this to @mroderick

**Comment by mroderick** [comment]
@freethejazz thank you for reporting this.

Hopefully my pull request to update to latest JSCS will fix the issues and remove any doubt on how to lint the files.

**Comment by freethejazz** [comment]
Cool, thanks @mroderick!
