### ISSUE TITLE
Problem when requiring Sinon through Node

### ISSUE THREAD

**Issue by chiefGui** [cjohansen/Sinon.JS#717]
I just have the following line:

```js
var sinon = require ('sinon');
```

Then:

> /node_modules/sinon/lib/sinon.js: /node_modules/sinon/lib/sinon/spy.js: /node_modules/sinon/lib/sinon/call.js: /node_modules/sinon/lib/sinon/match.js: undefined is not a function

Someone knows what is this?

*NOTE: This is a summarized scenario. I'm calling Sinon in a Jest test spec, but doesn't matter where I call it—the error is always there.*

**Comment by mroderick** [comment]
It would be easier to reproduce if you shared which version of Sinon and node you're using

**Comment by chiefGui** [comment]
Sorry about that, @mroderick.

Node v0.12.0
Sinon v1.14.1

**Comment by gyandeeps** [comment]
It works fine for me.
I have the same config except I use it with `mocha` test.

**Comment by chiefGui** [comment]
That's weird, @gyandeeps. But I can't figure out what's happening.

**Comment by GCheung55** [comment]
Have your tried uninstalling, cleaning NPM cache and reinstalling?

Can you paste verbose install logs?

**Comment by chiefGui** [comment]
Seems like the problem is happening with Sinon + Jest, because now I'm using Mocha and everything's going well. The point is: I don't know if is something Jest or Sinon-related. Ideas?

But so far, the "bug" is fixed.
