### ISSUE TITLE
How to stub a function of a private object

### ISSUE THREAD

**Issue by T1m1** [cjohansen/Sinon.JS#737]
Hello,

i have a private database object and want to stub a function called like 'this.db.getUsers()'.

This is my code created with TypeScript:
https://github.com/locator-kn/backend-user/blob/backend-user-2/src/plugin.ts#L77

And my test without stub:
https://github.com/locator-kn/backend-user/blob/backend-user-2/test/test.js#L49-L68

If I extract the functionality in another function, It will be possible to stub them. 
```javascript
        stub.User = sinon.stub(Plugin.prototype, 'testExtract').returns([]);
```

But It is possible to stub the private database instance without creation of an extracted function?

I would be glad if someone could help me.

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
