### ISSUE TITLE
Sinon method chaining weird behaviour

### ISSUE THREAD

**Issue by hanhpho** [cjohansen/Sinon.JS#739]
Sinon.js (v1.14.1) has a weird behaviour in method chaining, not sure it's meant to be or a bug:

This ([JSBin](http://jsbin.com/qoyesorivo/1/edit?js,console)):
```
var myStub = sinon.stub().withArgs(1).returns("one").withArgs(2).returns("two");
```
Will always return "two" no matter what argument you call ``myStub`` with.

On the other hand, this ([JSBin](http://jsbin.com/jeravaquke/1/edit?js,console)):
```
var myStub = sinon.stub();
myStub.withArgs(1).returns("one").withArgs(2).returns("two");
```
works fine. I'm not sure that SinonJS supports chaining or not.

Thanks, guys.

**Comment by mantoni** [comment]
The "implementation detail" behind this is, that `withArgs` and `returns` returns a "behavior" and not the stub instance. The behaviors can be chained. In your first snippet, you assign a behavior instance to `myStub`.

I can see that this is not really intuitive, but it's not a bug. Maybe it could be clarified in the docs.

**Comment by hanhpho** [comment]
Thanks a lot @mantoni.
