### ISSUE TITLE
stub method that changes byref parameter

### ISSUE THREAD

**Issue by yoavniran** [cjohansen/Sinon.JS#742]
Im using a dependency (path-to-regexp) in my node app that id like to stub.

This module provides a method that does optionally two things. one is returning a string and second is optionally update an array that is passed to the method as the second parameter.

Putting aside the debatable design decision of the module owner to make this function do two things, I don't see a way for me to make the stub do these two things.
I can of course control the return value but I don't see an option to tell Sinon to update the array I'm passing as the second parameter with mock data.

Any ideas?

**Comment by mantoni** [comment]
If you need two different behaviors, you might need two test cases, each defining one.

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

**Comment by yoavniran** [comment]
hmmm. perhaps I wasnt clear in my description... ?
This is very much a feature discussion since I dont see a way, definitely not from the docs, for how you can set up a stub to update a passed in parameter. And that seems like a missing feature. no?

thanks

**Comment by mantoni** [comment]
I would try to solve this with a custom stub function: 

```js
var stub = sinon.stub(object, "method", func);
```

The `func` will be invoked instead of the original function.

**Comment by yoavniran** [comment]
thanks but in this specific case it wont work as there's not object to set up. the module simply returns a function thats being stubbed.
I would need the more declarative way similar to "callsArg"...

**Comment by mantoni** [comment]
I don't understand the problem, apparently. Please post on the mailing list. If you want to suggest an API improvement, please open a new issue with a specific suggestion.

**Comment by yoavniran** [comment]
done.
https://groups.google.com/forum/#!topic/sinonjs/HqFzMk9ZgnE
