### ISSUE TITLE
Spy on WebSocket construction does not work

### ISSUE THREAD

**Issue by artemave** [cjohansen/Sinon.JS#743]
Reposting [this SO question](http://stackoverflow.com/questions/30020033/sinon-spy-on-websocket):

I am trying to spy on WebSocket construction with the following code ([requirebin](http://requirebin.com/?gist=12120d41a12bb90e7c62)):

    sinon = require('sinon');
    
    sinon.spy(window, 'WebSocket');
    // throws an error (see console)
    new window.WebSocket("ws://example.com");

In Chrome it fails with `Uncaught TypeError: Failed to construct 'WebSocket': Please use the 'new' operator, this DOM object constructor cannot be called as a function.` 

In Safari and PhantomJs it fails with `TypeError: Attempted to wrap object property WebSocket as function`

What am I doing wrong?

**Comment by mroderick** [comment]
Native objects are notoriously unreliable as spying/stubbing targets.

If you're working with a level of indirection like Socket.IO, then I'd recommend targeting that for spying/stubbing. There are examples of how to do this with Sinon.JS.

If you're working closer to the metal, then I'd recommend using a very thin wrapper around the target natives, to allow spying/stubbing.

I created [wrapple](https://github.com/mroderick/wrapple) for this purpose, but it's simple enough to create your own.

```javascript
// totally making things up here
function WrapWebSocket(){
    return window.WebSocket;
}

// in your code
function init(){
    var WS = WrapWebSocket();
    var ws = new WS();
}

// in your test
var spy = sinon.spy();
sinon.stub(window, 'WrapWebSocket', function(){
    return spy;
});
init();
assert(spy.calledWith('someurl');
```

**Comment by artemave** [comment]
Thanks for the explanation, now I understand what the problem is. 

Wrapple seems like a reasonable workaraound. Thanks again!
