### ISSUE TITLE
sinon.match only works for same instance of sinon

### ISSUE THREAD

**Issue by Havvy** [cjohansen/Sinon.JS#748]
If there are two instances of sinon, say sinon_a and sinon_b, then using sinon_a.match() values on objects from sinon_b will always fail. This is most probably due to usage of instanceof to determine whether the value is a sinon.match() value.

### ./index.js
```javascript
var sinon_a = require("sinon");
var sinon_b = require("indirect-sinon").sinon;

var spy = sinon_a.spy();
spy.call("abc", 123);

// Works
assert(spy.getCall(0).calledWith(sinon_a.match(/abc/), 123));

// Fails
assert(spy.getCall(0).calledWith(sinon_b.match(/abc/, 123));
```

### ./node_modules/indirect-sinon/index.js

```javascript
module.exports = { sinon: require("sinon") }
```

With `./node_modules/sinon` and `./node_modules/indirect-sinon/sinon` both being copies of the same version of sinon. E.g. in `.` do `npm install sinon` and in `./node_modules/indirect-sinon`, also do `npm install sinon`.

----

I his this locally because one of my mocks (not sure if that's the technical term) is shared between different packages, and I decided to have the mock depend on sinon. Then the packages themselves also have sinon, and since I'm not using npm3, they don't get deduplicated, so I have different copies of the same package.

Note that npm3 won't magically solve this issue. It's still possible to create by clearing the require() cache and then requiring sinon again.

**Comment by mantoni** [comment]
The reason why this doesn't work is that our deep equals check identifies matchers by inspecting the prototype chain. In general we have to rely on Sinon objects being passed into other Sinon functions to come from the same module instance. To make this work, we'd have to invest a lot of work in the whole library.
Since this is also a very rare use case, I don't think we're ever going to support this.

**Comment by ljharb** [comment]
Couldn't this be trivially fixed by using `Symbol`s instead of `instanceof` to identify Sinon objects?

**Comment by mroderick** [comment]
> Couldn't this be trivially fixed by using Symbols instead of instanceof to identify Sinon objects?

Sinon.JS is designed to have very wide support, think ES3

**Comment by ljharb** [comment]
Sure - then it could be conditionally fixed in newer engines, and it'd still be an issue in older ones?

**Comment by mantoni** [comment]
Like I said, we're not going to make it possible to call Sinon methods on extraneous Sinon objects. Be there symbols or whatever theoretical possibility. Theres a maintenance price tag on this feature that is too expensive.
