### ISSUE TITLE
An aborted XHR does not have responseHeaders

### ISSUE THREAD

**Issue by delitescere** [cjohansen/Sinon.JS#749]
After aborting an XHR, there should be an empty `responseHeaders` object available. This is because after a send, the abort can occur. An `onReadyState` is fired and a callback that checks if `readyState == 4` that proceeds to check `responseHeaders`.

In a browser, there is an empty `responseHeaders` after an aborted XHR. In Sinon, it is `undefined`.

A PR is coming that fixes it (with tests).

**Comment by mroderick** [comment]
The PR has been merged, thanks!

**Comment by delitescere** [comment]
Cheers :beers:
