### ISSUE TITLE
Stubbing functions with Sinon

### ISSUE THREAD

**Issue by jayasimhan** [cjohansen/Sinon.JS#753]
The Sinon documentation explains how we can stub methods in an object. But how do we use Stubs if the module exports a function and not an object? Here is an example.

The popular `request` module can be used in two ways

1.

	```
		myfunction(data,callback){
		  var requestParams = {
		    method: "POST",
		    json: data,
		    url: "http://localhost/test"
		  };
		  request(data,function(err,res,body){
		    callback(err,body);
		  });
		};
	```
2.

	```
		myfunction(data,callback){
		  var requestParams = {
		    json: data,
		    url: "http://localhost/test"
		  };
		  request.post(data,function(err,res,body){
		    callback(err,body);
		  });
		};
	```
How would we mock the request function when the code uses `request` using the first technique?

**Comment by mroderick** [comment]
This question comes up at intervals, I'll put it near the top of the list of things I'd like to write more documentation for.

For npm you can use https://github.com/thlorenz/proxyquire or similar. Michael Feathers would call this a [link seam](http://www.informit.com/articles/article.aspx?p=359417&seqNum=3).

It's not elegant, but doable.

Once you have that in place, you can use Sinon as you normally would.

In the long run, you might want to move your architecture towards *object seams*, but it's a solution that works today. Similar projects exist for RequireJS: [Squire.js](https://github.com/iammerrick/Squire.js/), [bogus](https://github.com/mroderick/bogus).

**Bonus**: there's even a Sinon example: https://github.com/thlorenz/proxyquire/tree/master/examples/sinon

--- 

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
