### ISSUE TITLE
Using sinon.useFakeTimers cause bluebird promises to fail

### ISSUE THREAD

**Issue by demetriusnunes** [cjohansen/Sinon.JS#754]
My test suite uses sinon.useFakeTimers in some tests. We also rely on bluebird A+ promise library.

After the latest version bump of bluebird to 2.9.26, all tests using sinon.useFakeTimers fail. Reverting bluebird back to 2.9.25 fixes the problem.

**Comment by gyandeeps** [comment]
They have fixed it in 2.9.27
