### ISSUE TITLE
Stubbing the same method on more than one consecutive tests fails

### ISSUE THREAD

**Issue by gmahomarf** [cjohansen/Sinon.JS#755]
I've got sample code here: <a href="https://gist.github.com/gmahomarf/1dc124c6d3a0555c7f0b" target="_blank">gist</a>

The situation is as follows: I've got a module (**someModule** in gist) that has two methods that fetch data from a store. Both methods use the same query-like method (**obj.method** in gist) from another module (**obj** in gist) to query the data store (using callbacks). I've written a test for both methods in **someModule**, and attempted to create a stub for **obj.method** with specific args before each test, which is then reset and restored after each test. 

The first test runs fine, but the second one times out (regardless of the order I run them in, only the first one to run works). I debugged everything, and found that when the second test calls **obj.method**, the invoke method called for the underlying spy has some weird behavior. Upon reaching this line <a href="https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/spy.js#L155" target="_blank">spy.js#L155</a>, `this.fakes` resolves to an array that contains one fake, but the matchingArguments property for it contains the args from the first test's stub, instead of the second one.

Is this a bug, or am I just missing something in how I'm creating and cleaning my stubs?

**Comment by mantoni** [comment]
This seems strange. Can you post a full runnable example that reproduces the issue? It's kind of hard to try and reproduce by emulating everything in my head.

**Comment by gmahomarf** [comment]
Sure thing. Give me a few minutes, and I'll edit this post with some new gists

**Comment by gmahomarf** [comment]
I'll go ahead and close this issue. As I was working on creating as close an example as possible, and getting frustrated because the example DID work properly, I realized the problem was in the way one of my modules is built, not with sinon. Thanks for the quick response, anyways. Love the work you've done with sinon.

**Comment by mantoni** [comment]
:+1:
