### ISSUE TITLE
AssertionError when testing controller, service and $http with fakeServer

### ISSUE THREAD

**Issue by nottinhill** [cjohansen/Sinon.JS#756]
### This is my controller

    $scope.signIn = (user) ->
        UserService.signIn(user)

### This is my UserService

    angular.module('myApp').factory 'UserService', [
      '$http',
      ($http) ->
        {
          signIn: (user) ->
            $http.post('/user/signin', user)
            .success (data) ->
              console.log data
            .catch (error) ->
              console.log error
        }
      ]

### This is my test

    it 'should call UserService through $scope.signIn', ->

        server = sinon.fakeServer.create();
        server.respondWith("POST", "/user/signin",
          [200, { "Content-Type": "application/json" },
           '[{ "id": 12, "comment": "Hey there" }]'])

        callback = sinon.spy()
        spyOnUserService = sinon.spy(UserService, 'signIn')

        mockScope.signIn("/user/signin", callback)
        server.respond()

        assert(spyOnUserService.calledWith(callback))

This is what happens:

`AssertionError: Unspecified AssertionError`

What am I doing wrong. How to test my service/controller duo properly for every possible scenario e.g. error and success promises.

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
