### ISSUE TITLE
No pkg/ folder in 1.15.0.

### ISSUE THREAD

**Issue by treshugart** [cjohansen/Sinon.JS#761]
Hey guys, not sure if you meant to do this, but releasing 1.15 to NPM has broken anybody using [karma-sinon-chai](https://github.com/treshugart/karma-sinon-chai). They expect `pkg/sinon.js` to be present. In `1.14` it is and in `1.15` it's not.

**Comment by nfroidure** [comment]
Same here, please respect semver...

**Comment by eXaminator** [comment]
Same here! +1

**Comment by mharmuth** [comment]
+1

**Comment by micha149** [comment]
:+1: Same here.

Is anybody already on it?

**Comment by treshugart** [comment]
Just so you guys know, you should be able to restrict Sinon to 1.14.1 in your `peerDependencies` until this is fixed.

**Comment by mokkabonna** [comment]
+1

**Comment by nfroidure** [comment]
@treshugart wasn't aware of this, but it just make npm install to fail in my case so i reverted to karma-sinon-chai 0.2.0 temporarly

**Comment by micha149** [comment]
@treshugart Isn't `dependencies` or `devDependencies` the right place to fix on sinon version 1.14.1. I ever thought the meaning of `peerDependencies` is *I only work if you depend on sinon@1.14.1*…

**Comment by treshugart** [comment]
It's a hack but it seemed to work for me.

**Comment by Kuniwak** [comment]
+1

**Comment by sulmanen** [comment]
+1

**Comment by cjohansen** [comment]
Certainly unintentional. Trying to push out 1.15.1 now to address the issue. Sorry guys.

**Comment by zephor** [comment]
`pkg/sinon.js` still seems to be missing from 1.15.1. Should we be expecting it to be there?

**Comment by ndrisso** [comment]
+1

**Comment by erikmunson** [comment]
+1 This is still not working in 1.15.1 and is causing a ton of trouble. When can we expect this to be fixed?

**Comment by sanimalp** [comment]
+1

**Comment by qknudsen** [comment]
+1

**Comment by jatwork** [comment]
+1

**Comment by TheSavior** [comment]
:+1: Broke us too.

**Comment by cjohansen** [comment]
@mroderick @mantoni any ideas? I just did a normal `npm publish`, has something changed that would cause this?

**Comment by mantoni** [comment]
@cjohansen I did see something similar occasionally in our company setup with an internal npm registry. Some files wouldn't show up in the package. Usually the packages only have the package.json and the README. Just doing another `npm publish` fixed the issue. Maybe try removing `node_modules`, do a fresh install and then publish again?

**Comment by cjohansen** [comment]
1.15.2 is out, and just as broken. WTF? @mantoni could you try publishing?

**Comment by cjohansen** [comment]
Figured it out! It seems we now have a `files` property in `package.json`, which changed the files that were included. Fixed it and pushed 1.15.3.

**Comment by Kuniwak** [comment]
Thank you so much! :tada:
I can find `pkg/sinon.js` on v1.15.3.

**Comment by nfroidure** [comment]
:clap:

**Comment by zephor** [comment]
works like a charm, thanks!

**Comment by sulmanen** [comment]
:clap: works :8ball: rox!
