### ISSUE TITLE
tests fail with "ReferenceError: Can't find variable: sinon" with v1.15

### ISSUE THREAD

**Issue by NShewmaker** [cjohansen/Sinon.JS#762]
I run unit tests with Karma+Mocha+Chai+Sinon+PhantomJS. They stopped working when npm picked up v1.15 of sinon (as a peer dependency of karma-sinon). Every test needing sinon fails with

    PhantomJS 1.9.8 (Linux 0.0.0) ... FAILED
        ReferenceError: Can't find variable: sinon

If I add an explicit dependency for "sinon" and set the version to "=1.14.1", the tests work again.

If you need more information, just ask.

**Comment by gyandeeps** [comment]
here is the reason #761

**Comment by NShewmaker** [comment]
Yes, thanks. Fixed in 1.15.3.
