### ISSUE TITLE
clearInterval erroneously clears setTimeout

### ISSUE THREAD

**Issue by rogierschouten** [cjohansen/Sinon.JS#766]
I had a bug in my code where I did a setTimeout and then tried to clear it with clearInterval. This passed all my unittests because sinon doesn't care about this difference.

The browser also doesn't care, but Node.JS does. It leads to a timer that is not cleared (and therefore my process did not exit).

I think it would encourage good coding practice without sacrificing any valid use cases if Sinon checked whether the setTimeout was properly matched to clearTimeout and setInterval to clearInterval.

**Comment by mantoni** [comment]
I agree. This could help find bugs that are otherwise hard to track down. The code that is used by Sinon for timers now lives here: https://github.com/sinonjs/lolex
Can you put a pull request together for this?

**Comment by rogierschouten** [comment]
Unfortunately not at the moment I'm under too much pressure

**Comment by rogierschouten** [comment]
The fix for this is PR #20 on the lolex module

**Comment by rogierschouten** [comment]
This is resolved in sinon 1.16.0
