### ISSUE TITLE
Set Request Payload in the Fake Server request 

### ISSUE THREAD

**Issue by raghunathsanam** [cjohansen/Sinon.JS#776]
Hi,
   I have a scenario where a same url  with different RequestPayload will return different Response. Is there a way to set the Request payload with sinon fakeserver?

           this.server.respondWith("POST", "/url", [
              200,
              { "Content-Type": "application/json" },
                 JSON.stringify([{"key":"value",....}
              ])
            ])
I tried it in different ways without success. Please let me know.

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
