### ISSUE TITLE
Proposal: Stub non-enumerable properties when only object is given

### ISSUE THREAD

**Issue by traviskaufman** [cjohansen/Sinon.JS#777]
Using sinon v1.15.3, the following code snippet does not work

```javascript
class Foo {
  doSomething() {
    var thing = 0;
    // do stuff with thing...
    return thing;
  }
}

const fooStub = sinon.createStubInstance(Foo);
fooStub.doSomething.returns(1);
```

The last line throws a `TypeError`, saying that `doSomething` does not have a `returns` method. This is due to the fact that function defined in class expressions are attached as [non-enumerable properties](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation) (see step 21.a), but [within sinon.stub](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/stub.js#L51-L55) a `for..in` loop is used, meaning any non-enumerable property is excluded. 

I think it would help with the future-forwardness of sinon to use something like `Object.getOwnPropertyNames` instead of `for..in` when using stub with only an object, because it would allow `createStubInstance` to interop seamlessly with class definitions, and I would be happy to submit a PR for this. I was just wondering if there are any arguments against stubbing non-enumerable properties and if so what would be a good solution to allow stubbing them in certain cases?

**Comment by traviskaufman** [comment]
any feedback on this?

**Comment by mantoni** [comment]
Thanks for pinging again. The reason against `Object.getOwnPropertyNames` is browser support and that it does not enumerate on prototype properties. We can use feature detection to make sure it doen't break in older browsers, but it might break for some users if you're only stubbing own properties.

**Comment by traviskaufman** [comment]
Thanks for the feedback!

That's a great point about prototype properties. However, as people begin using ES2015 / `class` more, `for .. in` will simply skip over those properties anyway since they're non-enumerable. Furthermore, the current implementation won't work for a lot of native objects in modern browsers, e.g.

```js
var fakeArray = sinon.createStubInstance(Array);
fakeArray.map.returns([1,2,3]); // throws a TypeError
```

We could do something like this:

```js
if (typeof property === "undefined" && typeof object == "object") {
  sinon.walk(obj, function(value, prop) {
    if (typeof value === 'function') {
      stub(object, prop);
    }
  });
}

return object;
```

Where `sinon.walk` might look like

```js
function walk(obj, iterator, context) {
  var proto, prop;
  if (typeof Object.getOwnPropertyNames === 'function') {
    Object.getOwnPropertyNames(obj).forEach(function(k) {
      iterator.call(context, obj[k], k, obj);
    });
    proto = Object.getPrototypeOf(obj);
    if (proto) {
      walk(proto, iterator, context);
    }
    return;
  }

  for (prop in obj) {
    iterator.call(context, obj[prop], prop, obj);
  }
}
```

**Comment by mantoni** [comment]
@cjohansen @mroderick

**Comment by cjohansen** [comment]
Seems alright to me!

**Comment by traviskaufman** [comment]
Great! One question though: should we not stub out the methods on `Object.prototype`? Stubbing things like `valueOf` and `toString` may be problematic when it comes to formatting.

**Comment by cjohansen** [comment]
Sounds like a good idea.

**Comment by nii236** [comment]
Will this be soon merged into the main Sinon JS line? It took me awhile to find this issue and it caused me problems as I'm working in ES2015 syntax at the moment.
