### ISSUE TITLE
Stubbing same file exports

### ISSUE THREAD

**Issue by ekmartin** [cjohansen/Sinon.JS#780]
Is there any way to get this to work?

moduleA.js:
```js
export function first() {
  console.log('first');
}

export function second() {
  first();
  console.log('second');
}
```

test.js:
```js
import * as moduleA from './moduleA';

sinon.stub(moduleA, 'first').returns('stubbed');
moduleA.second(); // will log first, second (not stubbed, second);
```

It would work if first and second were in two different files, but not when they're exported from the same file.

**Comment by mantoni** [comment]
Well, that is because your calling the local reference of `first`. You would have to invoke it like `exports.first()` in order to invoke the stub.

**Comment by ekmartin** [comment]
I see, thank you for the quick answer. I guess the only option is to move it out of the file or use something like [rewire](https://github.com/jhnns/rewire) then, as it's kind of hacky to refer to it with exports (especially when using ES6 modules where you don't really use `exports`).
