### ISSUE TITLE
spy of a stub doesn't respect 'onCall'

### ISSUE THREAD

**Issue by joseph-lansdowne-hp** [cjohansen/Sinon.JS#782]
With version 1.15.4, Node.js 0.10.33, creating a spy of a stub with call-specific behaviour loses the call-specific behaviour.  Test case:

```javascript
var sinon = require('sinon')
var f = sinon.stub().returns(1)
f.onFirstCall().returns(2)
var g = sinon.spy(f)
console.log(g())
console.log(g())
```

Should print 2, 1; prints 1, 1.  Calling `f` instead works as expected (prints 2, 1).

**Comment by mantoni** [comment]
You wrapped the stub in a spy. That makes no sense. This works as expected:

```js
var sinon = require('sinon')
var f = sinon.stub().returns(1)
f.onFirstCall().returns(2)

console.log(f()) // 2
console.log(f()) // 1
```

**Comment by joseph-lansdowne-hp** [comment]
The documentation says:

'sinon.spy can also spy on existing functions. When doing so, the original function will behave just as normal (including when used as a constructor) but you will have access to data about all calls.'

So maybe this should be changed to indicate that the original function doesn't behave as normal if it's a stub.

**Comment by cjohansen** [comment]
That is noted under the documentation for stubs.
