### ISSUE TITLE
Pass options to fakeServer.create

### ISSUE THREAD

**Issue by maxcal** [cjohansen/Sinon.JS#784]
One annoyance I have with the otherwise awesome fakeServer is that it does not take initialization arguments. What I want to be able to do is:

```js
server = sinon.fakeServer.create({
  autoRespond: true,
  autoRespondAfter: 1
});
```

Instead of; 
```js
server = sinon.fakeServer.create();
server.autoRespond = true;
server.autoRespondAfter = 1;
```

This seems pretty trivial to implement or am I missing something?

**Comment by mroderick** [comment]
If it's trivial, then it shouldn't take you long to make a pull request ;)

**Comment by maxcal** [comment]
I'm looking into it, but I'm totally new to the code base. Is there no tests for fakeServer?

**Comment by maxcal** [comment]
I guess the docs should be updated as well - are the `sinonjs.org` docs in another repository? I tried looking in the docs branch but that not it
.

**Comment by mroderick** [comment]
> I guess the docs should be updated as well - are the sinonjs.org docs in another repository? I tried looking in the docs branch but that not it

Yeah, that's a bit confusing.

https://github.com/sinonjs/sinon-docs

**Comment by maxcal** [comment]
I'll look into writing a PR for the docs but might take a while since I have 0 experience with clojure and Stasis.

**Comment by mroderick** [comment]
Me neither :(

**Comment by maxcal** [comment]
Thanks for your patience, I haven't contributed to many projects yet and don't have the workflow down quite yet.

**Comment by mroderick** [comment]
> Thanks for your patience, I haven't contributed to many projects yet and don't have the workflow down quite yet.

We all have to go down that path. We are very grateful for your contributions!

**Comment by cjohansen** [comment]
Nice work, both in the contributing and the receiving of said contribution :)

Re the docs: this was probably a mistake on my end, but the content is all just markdown: https://github.com/sinonjs/sinon-docs/tree/master/resources/docs

**Comment by maxcal** [comment]
The actual API documentation is in https://github.com/sinonjs/sinon-docs/blob/master/resources/docs/server.edn though?

**Comment by cjohansen** [comment]
Oh, right. My bad.
