### ISSUE TITLE
Update lolex to 1.2.1

### ISSUE THREAD

**Issue by vitalets** [cjohansen/Sinon.JS#786]
Currently sinon stick to lolex@1.1.0 that is very old (and does not work in phantomjs).

**Comment by mroderick** [comment]
> Currently sinon stick to lolex@1.1.0 that is very old (and does not work in phantomjs).

Could you describe what doesn't work in more detail?

**Comment by vitalets** [comment]
Yes, exactly this line:
https://github.com/sinonjs/lolex/blob/v1.1.10/src/lolex.js#L92
breaks `Date.now()` in phantomjs 1.9.8 because `now` is considered own property and overwritten back to source function.
Example:
````js
// phantomjs
Object.keys(Date) // ['now', 'UTC', 'parse']
// chrome
Object.keys(Date) // []
````
it was fixed in lolex 1.2.1 (moved before properties overwriting):
https://github.com/sinonjs/lolex/blob/v1.2.1/src/lolex.js#L84

**Comment by mroderick** [comment]
We still need to update to use new lolex

**Comment by vitalets** [comment]
Thank you!
