### ISSUE TITLE
Stub a function for only one argument

### ISSUE THREAD

**Issue by gyandeeps** [cjohansen/Sinon.JS#791]
So basically I have an function whose behavior I want to stub only if the argument is equal to something.
Example

```js
var foo = {
    bar: function(arg1){
        return true;
    }
};

var barStub = sinon.stub(foo, "bar");
barStub.withArgs("test").returns("Hi");

// Expectations
console.log(foo.bar("test")); //works great as it logs "Hi"

// my expectation is to call the original function in all cases except 
// when the arg is "test"
console.log(foo.bar("woo")); //doesnt work as it logs undefined
```

**Comment by mroderick** [comment]
I am having a hard time imagining when I would need such functionality.

Do you have a less synthetic example that might make me understand the need for this?

**Comment by gyandeeps** [comment]
In my use case, i have one function which reads files. So I wanted to fake the response when it tries to read file `xxxx.txt` but for all the rest I want the function to behave as it is.

Now in [Jasmine](http://jasmine.github.io/2.3/introduction.html#section-Spies:_<code>and.callThrough</code>) they have `callThrough` function which allows you to call the original function.

**Comment by gyandeeps** [comment]
Same as https://github.com/cjohansen/Sinon.JS/issues/735

**Comment by mroderick** [comment]
> I guess we can close this as we know the answer.

Yeah. From your use case it sounds like your function has more than one responsibility.

**Comment by mocheng** [comment]
Even tough this issue is closed, I just want to post my case to prove it is necessary.

In my case, the program is run with `babel-register` and there is one unit test need to stub `readFileSync` for given filename and `proxyquire` to stub required module. However, `babel-register` would find `.babelrc` and parse it during execution. As a result, below code will fail.

```
      stub(fs, 'readFileSync').withArgs(givenPath).returns(JSON.stringify(h3oConfig));
      const foo = proxyquire('./foo', stub); // this will fail on reading .babelrc
```

It sounds that stub would better to have only customized returned value on given args.

**Comment by mantoni** [comment]
@mocheng You can program the stub to have different behavior for different arguments like this:

```js
stub(fs, 'readFileSync')
fs.readFileSync.withArgs(givenPath).returns(JSON.stringify(h3oConfig));
fs.readFileSync.withArgs('.babelrc').returns('#');
```

**Comment by mocheng** [comment]
@mantoni Thanks. 
It just looks tedious to mock `.babelrc` and my `.babelrc` has quite a lot of stuff.
Now, I just totally rely on `proxyquire` for this case.

**Comment by mantoni** [comment]
@mocheng There is a new feature that [just landed on master](https://github.com/sinonjs/sinon/pull/1234) which allows to call through to the original implementation. It's not in a release yet, and it will only be supported in Sinon 2. You can point your dependency to master for now.

**Comment by mocheng** [comment]
@mantoni  cool. thanks!
