### ISSUE TITLE
FakeXMLHttpRequest not being used with jQuery 1.x

### ISSUE THREAD

**Issue by heldinz** [cjohansen/Sinon.JS#792]
I have a test setup using jsdom (actually jsdom-no-contextify) and Sinon's `fakeServer` to handle AJAX calls. In my globals setup, after initializing the DOM, I set `global.XMLHttpRequest = global.window.XMLHttpRequest`.

In a `before` function, I set the following before setting up my responses:

      sinon.xhr.supportsCORS = true;
      server = sinon.fakeServer.create();

This worked great with jQuery 2.x. However, I recently switched to jQuery 1.x because I need to support IE8, and my AJAX tests immediately stopped working. Every AJAX call results in a "No transport" error.

Debugging shows that that `FakeXMLHttpRequest` is being used as expected with jQuery 2.x, but not with jQuery 1.x. It's not clear to me why. Have I made a mistake with my setup or is there a bug in Sinon (or jQuery)?

**Comment by heldinz** [comment]
I found the issue. While jQuery 2.x sets `jQuery.ajaxSettings.xhr` as `new XMLHttpRequest()`, [jQuery 1.x][jq] sets it as `new window.XMLHttpRequest()`, thereby bypassing the FakeXMLHttpRequest.

I solved the issue by storing jQuery's initial `jQuery.ajaxSettings.xhr` value in a variable, then setting `jQuery.ajaxSettings.xhr` to a new value of `new XMLHttpRequest()` in my setup methods, and finally restoring it to its initial value in my teardown methods.

[jq]: https://github.com/jquery/jquery/blob/1.11-stable/src/ajax/xhr.js#L187

**Comment by mroderick** [comment]
Thank you for following up with a detailed description of the resolution. jQuery really needs to fix this issue...

**Comment by heldinz** [comment]
I've added my 2c over at https://github.com/jquery/jquery#2453, where @Krinkle already opened an issue regarding fake timers. We'll see, they might prefer me to open a new issue, but the description "jQuery 1.x breaks Sinon.JS XHR mock" certainly fits.

**Comment by heldinz** [comment]
Apparently [this will become an issue again with jQuery 3.x][jq3]:

> On the contrary - it's now included in jQuery 3.0 (a continuation of the 2.x line) as we support running jQuery in non-browser environments passing custom window implementation to the jQuery factory; we even have tests for it. Both branches use window.XMLHttpRequest now, we only assume JavaScript globals, not browser ones.

[jq3]: https://github.com/jquery/jquery/issues/2453#issuecomment-125539476
