### ISSUE TITLE
useFakeTimers doesn't fake performance.now()

### ISSUE THREAD

**Issue by panrafal** [cjohansen/Sinon.JS#803]
As using perfomance.now() is more robust for timeouts than Date.now(), it'd be nice if creating a `clock` would "pause" or synchronize `performance.now` to provided now value and calling `clock.tick` would move it.

**Comment by mroderick** [comment]
Why would you use `Date.now()` or `performance.now` for `setTimeout`?

Can you give a usage example?

**Comment by panrafal** [comment]
@mroderick "for timeouts" I've meant when you check if enough time has passed:

```javascript
var started = performance.now();

function calledLater() {
  if (performance.now() - started > 5000) {
    // do something
  }
}
```

In my use case I'm checking if some visual feedback was visible to the user long enough before removing it. Performance.now() guarantees it'll only go forward and it's not possible to break it by adjusting the system clock.

I've fixed this for myself by stubbing performance.now() with Date.now() `sinon.stub(performance, 'now', Date.now)`

Since posting this I've found that timers are handled by lolex, so probably it's better to move this issue there?

**Comment by mroderick** [comment]
Why not just use [`setTimeout`](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout)?

```javascript
setTimeout(function calledLater(){
    // do something
}, 5000);
```

**Comment by panrafal** [comment]
It's not an operation that should be run after some time, but a check if sufficient amount of time has passed.

**Comment by mroderick** [comment]
> It's not an operation that should be run after some time, but a check if sufficient amount of time has passed.

`setTimeout` guarantees that sufficient time has passed, that's what it's for ...

**Comment by mroderick** [comment]
In any case, pull requests to `lolex` would be most welcome

**Comment by mroderick** [comment]
I am closing the issue here. If you feel like contributing to `lolex`, please open a pull request in that repository.
