### ISSUE TITLE
Standalone sinon.js on npm

### ISSUE THREAD

**Issue by Rob--W** [cjohansen/Sinon.JS#805]
I needed standalone version of sinon.js so that it could be used in a client-side project that manages dependencies via npm. But `npm install sinon` does not provide any readily usable file, and the online version of sinon.js is hosted on http, so directly linking to it is not feasible either (because it cannot be loaded on https pages).

To be able to use the library, I published the package on npm (and every previous version, in case others need it): https://www.npmjs.com/package/sinon-dist
Could you mention npm-dist in the README, for others in a similar situation?

**Comment by mantoni** [comment]
You can find the Sinon files in `node_modules/sinon/pkg/sinon-{version}.js`. There is no need for a separate package. This might even confuse people who are searching for sinon on npm. Therefore I would prefer `sinon-dist` to be removed.

If things don't work out with the `pkg` files, please open a new issue. We are willing to help.

**Comment by Rob--W** [comment]
Thanks, I didn't know about `pkg/sinon-version.js`, because it was **not documented** anywhere (not in README.md, RELEASE.md, CONTRIBUTING.md or the website). I've marked all version in sinon-dist starting at 1.3.0 as deprecated, could you update your documentation and point to `pkg/sinon.js`?

```sh
npm deprecate sinon-dist@'>=1.3.0' 'sinon-dist is deprecated, use sinon instead: npm install sinon (the standalone file is in node_modules/sinon/pkg/sinon.js)'
```

I'm not sure if it's intentional, but your package on npm contains multiple versions of sinon. Since the `pkg/` was not documented anywhere, I suggest to clean the directory before distributing, and only have a single file called `sinon.js` (and maybe also `sinon-ie.js`, `sinon-timers.js`, `sinon-timers-ie.js`, `sinon-server.js`). I discourage the use of versioned files in the npm, because otherwise updating the dependency could require two changes: First in package.json (to bump the version), and then in the HTML/JS file that include the package.

Here's the listing for 1.15.4:

```sh
$ npm install sinon
sinon@1.15.4 node_modules/sinon
├── formatio@1.1.1
├── samsam@1.1.2
├── lolex@1.1.0
└── util@0.10.3 (inherits@2.0.1)
$ ls -Gg node_modules/sinon/pkg/
total 1288
-rw-r----- 1 190817 May  1 22:50 sinon-1.14.1.js
-rw-r----- 1 191076 Jun 10 08:26 sinon-1.15.0.js
-rw-r----- 1 191076 Jun 10 12:00 sinon-1.15.1.js
-rw-r----- 1 191698 Jun 27 09:18 sinon-1.15.4.js
-rw-r----- 1   4247 May  1 22:50 sinon-ie-1.14.1.js
-rw-r----- 1   4247 Jun 10 08:26 sinon-ie-1.15.0.js
-rw-r----- 1   4247 Jun 10 12:00 sinon-ie-1.15.1.js
-rw-r----- 1   4247 Jun 27 09:18 sinon-ie-1.15.4.js
-rw-r----- 1   4247 Jun 27 09:18 sinon-ie.js
-rw-r----- 1 191698 Jun 27 09:18 sinon.js
-rw-r----- 1  69361 May  1 22:50 sinon-server-1.14.1.js
-rw-r----- 1  69404 Jun 10 08:26 sinon-server-1.15.0.js
-rw-r----- 1  69404 Jun 10 12:00 sinon-server-1.15.1.js
-rw-r----- 1  70017 Jun 27 09:18 sinon-server-1.15.4.js
-rw-r----- 1   3911 May  1 22:50 sinon-timers-1.14.1.js
-rw-r----- 1   3911 Jun 10 08:26 sinon-timers-1.15.0.js
-rw-r----- 1   3911 Jun 10 12:00 sinon-timers-1.15.1.js
-rw-r----- 1   3911 Jun 27 09:18 sinon-timers-1.15.4.js
-rw-r----- 1   2961 May  1 22:50 sinon-timers-ie-1.14.1.js
-rw-r----- 1   2961 Jun 10 08:26 sinon-timers-ie-1.15.0.js
-rw-r----- 1   2961 Jun 10 12:00 sinon-timers-ie-1.15.1.js
-rw-r----- 1   2961 Jun 27 09:18 sinon-timers-ie-1.15.4.js
```

Thanks for your work on Sinon.js!

**Comment by mantoni** [comment]
Thank you! :+1:

You have some valid points there. I guess cleaning the `pkg` and having names without versions in it makes sense, but I'm not sure whether there was an intention behind this @mroderick @cjohansen ?

**Comment by mroderick** [comment]
Thank you @Rob--W for the detailed report!

Having several versions looks like an oversight to me.
I think it's time for an overhaul of what goes into `pkg/` version, there have been recent bug reports #793 that show that there are more broken things in that area.
