### ISSUE TITLE
Allow to test system time changes with Sinon.JS

### ISSUE THREAD

**Issue by rogierschouten** [cjohansen/Sinon.JS#808]
This is related to #215 which was closed without a solution. 

I would like to test some code that schedules a daily job. The code should try to detect and account for system clock changes. Therefore, I would like (just as in #215) to change the current time without triggering any timeouts, to simulate somebody changing the system clock while my program is running. Is this possible by now?

**Comment by mroderick** [comment]
There hasn't been any activity on the other issue since I closed it ~6 months ago. 

Do you want to take a stab at implementing it?

**Comment by rogierschouten** [comment]
Yeah I'll look at it in a few days. By the looks of it I should be changing the lolex module?

**Comment by mroderick** [comment]
> By the looks of it I should be changing the lolex module?

Yep, that's a good place to start :+1:

**Comment by rogierschouten** [comment]
I created a PR #22 to the lolex module at https://github.com/sinonjs/lolex/pull/22  to fix this. Sinon should simply also provide a setSystemTime() method on its clock and call the lolex setSystemTime()

**Comment by rogierschouten** [comment]
Can you also document this on the http://sinonjs.org/ website by the way? Thanks.

**Comment by rogierschouten** [comment]
This is resolved in Sinon 1.16.0
