### ISSUE TITLE
require('sinon') returns empty object in node

### ISSUE THREAD

**Issue by Strate** [cjohansen/Sinon.JS#814]
Hi!

I want to use `sinon` on node.js. I am do following:
```
var sinon = require('sinon')
```
After that `sinon` var is empty object. `global.sinon` is undefined.
What am I doing wrong?

**Comment by mroderick** [comment]
It would make it a lot easier for people to work on this issue if you describe the situation in greater detail and with more context.

Please see [reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue) for guidelines.

**Comment by Strate** [comment]
This problem happens together wih using `mocha`. To get `sinon` working I should launch `mocha` with extra `--require sinon` option. With that option regular `require('sinon')` works as expected.

I think this should be added to readme.

**Comment by mroderick** [comment]
Did you install sinon via npm? What does your `package.json` look like? What does your test file look like?

**Comment by Strate** [comment]
Sorry for my inconvience, but I can not reproduce that problem on clean test project. I think that it should be closed.
