### ISSUE TITLE
1.16.0 breaks setImmediate shims

### ISSUE THREAD

**Issue by fatso83** [cjohansen/Sinon.JS#821]
After upgrading to 1.16.x all code that relies on a setImmediate shim will fail with setImmediate being undefined. Version 1.15.4 is ok.

I uploaded an executable test of this on my [setImmediate-bug](https://github.com/fatso83/Sinon.JS/tree/setImmediate-bug) branch.

Verifying bug
```
git clone https://github.com/fatso83/Sinon.JS.git
git checkout setImmediate-bug
npm install
karma start \
        test/setImmediate-bug/karma.setImmediate.conf.js \
        --singleRun
```

Verify it was ok in 1.15.4
```
npm install sinon@1.15.4
karma start \
        test/setImmediate-bug/karma.setImmediate.conf.js \
        --singleRun
```

Tested with PhantomJS 1.9.2 and Chrome 44

**Comment by fatso83** [comment]
I now reworked my test so that it could be used with `git bisect`, and found the bad commit: 
```
curl -o test-script.sh https://raw.githubusercontent.com/fatso83/Sinon.JS/setImmediate-bug/test-script.sh
git bisect start v1.16.1 v1.15.4
git bisect run ./test-script.sh
```
results in (after some time) `7ecac06e0f1d7b76f05b35546da8d34219b21a79 is the first bad commit `

This is the commit where lolex is upgraded from 1.1 to 1.3, which makes sense, as I see this is where the faked timer utils have been extracted to. I will look into that package to see if the bug is there (quite likely).

**Comment by mroderick** [comment]
Nice work! I am curious to see where this rabbit hole will lead you

**Comment by fatso83** [comment]
Thanks, I found that this happens when something was introduced in lolex 1.2.1, but I'll dig some more over there :)

**Comment by fatso83** [comment]
Fix and an explanation is present sinonjs/lolex#26, and one can validate that it works by using the version in the PR: `npm install fatso83/lolex#setImmediate-shim-fix`

**Comment by dmitriiabramov** [comment]
i found this issue too.

lolex creates a key for `setImmediate` that has no value in it

so the code
```js
console.log(window.hasOwnProperty('setImmediate'), window.setImmediate);
require('sinon');
console.log(window.hasOwnProperty('setImmediate'), window.setImmediate);
```
will print
```
false undefined
true undefined
```

temp fix for that is
```js
require('sinon');
delete window.setImmediate;
```
