### ISSUE TITLE
How to use sinon.xhr.XMLHttpRequest in fakeServer.respondWith

### ISSUE THREAD

**Issue by duongphuhiep** [cjohansen/Sinon.JS#824]
On browser, the fake server must to reply using a fake response in a .json file

    var server = sinon.fakeServer.create({autoRespond: true, autoRespondAfter: 1000}); //simulate the connection latency to 1sec per request

    server.respondWith(function(request) {
       ...

      //the fake response comes from an external json file, 
      //we will get it with the original XMLHttpRequest
    
      var oReq = new sinon.xhr.XMLHttpRequest();
      oReq.open('get', fileToLoad);
      oReq.onload(function (e) {
      	request.respond(200, {"Content-Type": "application/json"}, oReq.responseText);  //Uncaught Error: INVALID_STATE_ERR - 4
      });

      oReq.send();
    }

But by the time the .json file is read, the request has been already closed, so set the respond will causes

    Uncaught Error: INVALID_STATE_ERR - 4
    verifyRequestOpened @ fake_xml_http_request.js:267
    setResponseHeaders @ fake_xml_http_request.js:426
    respond @ fake_xml_http_request.js:561
    server.respondWith.oReq.onreadystatechange @ fake-backend.js:48

How to make it work in this scenario?

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
