### ISSUE TITLE
Stub readonly properties

### ISSUE THREAD

**Issue by Rudloff** [cjohansen/Sinon.JS#829]
It would be useful to be able to stub readonly properties like ```navigator.battery```.

**Comment by mroderick** [comment]
you will need to add a little wrapper around the read only native then.

Example: https://github.com/mroderick/wrapple

**Comment by ljian3377** [comment]
> you will need to add a little wrapper around the read only native then.
> 
> Example: https://github.com/mroderick/wrapple

Could you be more elaborate? I can't see how wrapple solves the problem. Also I don't want to depend on a lib for this task.

The issue I am having is like this:
```
Class A {
    public readonly a: string
}

const aStub = sinon.createStubInstance(A);
sinon.stub(aStub , "a").get(() => "test"); 
```
It will throw 
```
 TypeError: Cannot stub non-existent own property url
      at Object.stub (....\node_modules\.pnpm\registry.npmjs.org\sinon\7.5.0\node_modules\sinon\lib\sinon\sandbox.js:315:19)
```
I haven't figured out a way to stub a field rather than a getter. Any advice?
