### ISSUE TITLE
`.calledWith()` returns true when no arguments are passed

### ISSUE THREAD

**Issue by brunops** [cjohansen/Sinon.JS#836]
Not sure if it works as design, but it doesn't seem like a consistent behavior, see the following code:

```js
var sinon = require('sinon');

var obj = {
    fn: function () {
        return 1;
    }
};

var stub = sinon.stub(obj, 'fn');

obj.fn(3);

console.log(stub.calledWith(3));         // true
console.log(stub.calledWith(5));         // false
console.log(stub.calledWith(undefined)); // false

// all calls make sense but this one
console.log(stub.calledWith());          // true
```

Is it expected to work like this?

**Comment by mantoni** [comment]
Well, it is supposed to match the specified arguments, bot requiring you to specify all of them. Taken to the extreme, this means that passing no arguments always returns true.

For exact argument matching, there is `calledWithExact`. It requires all the arguments to match.

**Comment by brunops** [comment]
Interesting, that makes sense to me. Feel free to close this then.

Thanks.
