### ISSUE TITLE
Stub API suddenly talks about spy methods

### ISSUE THREAD

**Issue by spinningarrow** [cjohansen/Sinon.JS#838]
In the [documentation about stubs](http://sinonjs.org/docs/#stubs), there's a listing of methods such as `stub.yieldsTo`, `stub.yieldsToOn` and so on. Suddenly in the middle there's reference to `spy` instead of `stub` - we have `spy.yield`, `spy.yieldTo`, `spy.callArg`, and `spy.callArgWith`. Following these 4, we go back to `stub.callsArgAsync`.

Looks like a typo to me which I'll be happy to fix. How does one make a PR to the documentation?

**Comment by spinningarrow** [comment]
My sincere apologies: it's mentioned in the contributing guidelines. Sorry!

**Comment by mroderick** [comment]
Closed via PR to `sinonjs/sinon-docs`
