### ISSUE TITLE
expect inside asynchronous function callback not working

### ISSUE THREAD

**Issue by PreethiBabu87** [cjohansen/Sinon.JS#839]
hi

Am trying to do an assertion with cai expect inside a callback of a function.
But expect succeeds in all scenarios. Below is my example code:
var testparams = '123';
logic.TestFunctionABC(testparams, function(err, data)
{
   console.log(data); //returns the correct data
   expect(data).to.equal('123') ;
  // above suceeds everytime even if i change to expect(data).to.equal('345');
});

does chai expect work inside asynchronous callback functions?
kindly help

**Comment by mroderick** [comment]
This looks like a usage question to me, and not even related to Sinon.JS.

I would imagine that your questions would get better answers in the [Chai.js user group](https://groups.google.com/forum/#!forum/chaijs)
