### ISSUE TITLE
[question] [help needed] Proper way to stub/spy for Node.js Error messages

### ISSUE THREAD

**Issue by hellboy81** [cjohansen/Sinon.JS#842]
I have to test if SUT throws custom error:

This error is thrown by SUT itself and not propagates another Error (for example database error).

In Assert I should check if exception thrown is (also first `callback`-Parameter not null and has appropriate type).

- `SPEC`:
 - `Arrange`:
   ```js
    // What is the best way to create stub  for MyCustomError constructor?
    errors = {MyCustomError: sinon.stub()}
   // Or may be with spy?
    errors = {MyCustomError: sinon.spy()}
    
   // Inject dependency with rewire into module to be tested
   // m_errors is a private module level variable
    myMod.__set__(m_errors, errors)
   ```
  - `Assert` that error object is MyCustomError 
     ```js
        // With chai should syntax
        err.should.be.instanceof(errors.MyCustomError)

         // with unexpected.js)
         expect(err, 'to be an', errors.MyCustomError)
     ```

- `SUT`

   `err` is an [Error class instance](https://nodejs.org/api/errors.html#errors_class_error)

    ```js
     return cb(new m_errors.MyCustomError(err))
     ```

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
